name: '@wpay/frames build'

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Git setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: NPM install
        run: npm install

      - name: NPM test
        run: npm run test
