name: '@wpay/frames build'

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: Git setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: NPM install
        run: npm install

      - name: NPM test
        run: npm run test

      - name: NPM Build
        run: npm run dist

      - name: Commit dist changes
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git add dist/ || echo "No changes to stage"
          git commit -m 'Updated dists' || echo "No changes to commit"

      # Can't be in a separate job as we need the results of any build to be included in
      # any published module.
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./scripts/tag.sh
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git push
          git push --tags
